### ISSUE TITLE
寻求911me的解决方案，i7-10870H  Gtx1650Ti  Ax201

### ISSUE THREAD

**Issue by WJH312121** [athlonreg/Thunderobot-Hackintosh#4]
寻求911me的解决方案，i7-10870H  Gtx1650Ti  Ax201

**Comment by YUNYIsa** [comment]
我有能用的efi,200rmb

**Comment by YUNYIsa** [comment]
wifi 电池 声卡都OK，睡眠容易睡死，触摸板不触控。

**Comment by athlonreg** [comment]
> 我有能用的efi,200rmb

到这做生意来了？

**Comment by chengnan049** [comment]
> 寻求911me的解决方案，i7-10870H Gtx1650Ti Ax201

在套陆的雷神QQ群看到消息说有了，群号是317496036，但是你这个独显是驱动不了的（实际上如果还不能用随便找几个同代的多试试就OK）

**Comment by YUNYIsa** [comment]
本来就有20年就有了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月12日(周六) 下午4:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [athlonreg/Thunderobot-Hackintosh] 寻求911me的解决方案，i7-10870H  Gtx1650Ti  Ax201 (#4)




  
寻求911me的解决方案，i7-10870H Gtx1650Ti Ax201
  
在套陆的雷神QQ群看到消息说有了，群号是317496036，但是你这个独显是驱动不了的（实际上如果还不能用随便找几个同代的多试试就OK）

**Comment by chengnan049** [comment]
> 我有能用的efi,200rmb

你可真敢，GitHub的开源精神可给你整坏了，小兵老吴等大佬包安装才这个价，你说的WiFi 电池 声卡容易的很，随便找一个都能，你一个触控板和睡眠还没解决的EFI都敢200，送你个6

**Comment by chengnan049** [comment]
> 本来就有20年就有了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年11月12日(周六) 下午4:20 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [athlonreg/Thunderobot-Hackintosh] 寻求911me的解决方案，i7-10870H Gtx1650Ti Ax201 (#4) 寻求911me的解决方案，i7-10870H Gtx1650Ti Ax201 在套陆的雷神QQ群看到消息说有了，群号是317496036，但是你这个独显是驱动不了的（实际上如果还不能用随便找几个同代的多试试就OK） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不是这个机型，没关注过
